//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstProject1.DB_Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public int eNo { get; set; }
        public string eName { get; set; }
        public Nullable<double> eSal { get; set; }
        public string eDep { get; set; }
        public Nullable<double> eAge { get; set; }
        public Nullable<int> eAdhar { get; set; }
    }
}
